### ISSUE TITLE
TypeError: SQL.Database is not a constructor

### ISSUE THREAD

**Issue by linonetwo** [citycide/trilogy#95]
## description

I'm writing a [plugin](https://github.com/linonetwo/zazu-firefox-bookmarks/blob/abcbf91b9aab68c6294c5df703af0d8d59e31f98/src/history/historySearcher.js#L14-L16) for https://github.com/tinytacoteam/zazu
And I'm writing es5.

### source

This works fine.

```js
const db = new Trilogy(historyDbPath)
```

While this not:

```js
const Trilogy = require('trilogy');

const db = new Trilogy(historyDbPath, {
    client: 'sql.js',
  });
```

### error

```
Cannot use 'new' with an expression whose type lacks a call or construct signature.ts(2351)
```

```
TypeError: SQL.Database is not a constructor
    at readDatabase (/Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/trilogy/dist/trilogy.js:125:14)
    at Object.create (/Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/trilogy/dist/trilogy.js:153:30)
    at Pool._createResource (/Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/generic-pool/lib/Pool.js:308:42)
    at Pool._ensureMinimum (/Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/generic-pool/lib/Pool.js:340:12)
    at Pool.start (/Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/generic-pool/lib/Pool.js:414:10)
    at new Pool (/Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/generic-pool/lib/Pool.js:128:12)
    at Object.createPool (/Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/generic-pool/index.js:11:12)
    at connect (/Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/trilogy/dist/trilogy.js:151:15)
    at new Trilogy (/Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/trilogy/dist/trilogy.js:1009:19)
```

## expected

Works as the same.

## actual

Maybe this works fine if I use `import`, but now I have to write `require`, and it doesn't work.

**Comment by citycide** [comment]
Interesting, glad to see `sql.js` has reached a stable version. I should have put a version restriction on the peer dep to account for this, but we'll do that now and make it `^1.0.0`.

**Comment by citycide** [comment]
FYI I had a hard drive fail on me recently, and I'm having a hell of a time getting `sqlite3` to build when cloning here.. Guess we've come full circle! If anyone would like to tackle this in a PR it would be very appreciated.

Make backups people 🤕

**Comment by linonetwo** [comment]
Actually, sql.js don't work properly in electron https://github.com/kripken/sql.js/issues/271 so I switch to `exec(sqlitebinary xxx)` to finish my plugin, So...

**Comment by citycide** [comment]
I finally got back a somewhat workable environment to look at this a bit - `node-gyp` is an awful experience..

And now I'm wondering how this came up at all. How did `sql.js@1.0.0` end up installed for you to cause this issue? trilogy 1.x's dependency on `sql.js` is `^0.4.0` which would only install up to `0.5.0`. I was able to install and pass all tests.

I'm also finding a separate issue in [kikobeats/osom](https://github.com/kikobeats/osom) where the author changed the node engine requirement from `>= 4` to `>= 8` in a minor version which breaks installation of trilogy, so we'll have to pin it to `2.2.2` (this library is removed in trilogy 2.x).

In any case I'm hoping to do some work on this over the weekend, to pin some dependencies at the very least.

**Comment by citycide** [comment]
I can't reproduce this but published `1.4.6` that updates a couple dependencies and fixes the problem with osom on newer Node versions.

**Comment by linonetwo** [comment]
Thanks for the update, if someone else tries to use my plugin and failed to use it, I will try `trilogy` again to fix my plugin.

Thanks for your packages, your `param.macro` is very useful to me!

**Comment by citycide** [comment]
@linonetwo glad to hear it, thanks :smile:
